<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gro</string>
	</array>
	<key>name</key>
	<string>Gro</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(?=//)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.gro</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>//</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.gro</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.number-sign.gro</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?:true|false)\b</string>
			<key>name</key>
			<string>constant.language.gro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?:dt|volume|just_divide|daughter|selected|id|ecoli|growth_rate|gro|division_size_mean|division_size_variance|gfp_saturation_min|gfp_saturation_max|lambda|rate|gfp|cost|rfp|yfp|cfp|rfp_saturation_min|yfp_saturation_min|cfp_saturation_min|rfp_saturation_max|yfp_saturation_max|cfp_saturation_max)\b</string>
			<key>name</key>
			<string>support.constant.gro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?:reset|clear_messages|message|signal|tostring|set|print|skip|rand|snapshot|head|tail|exit|atoi|atof|length|sin|cos|tan|rev|zip|makelist|sumlist|table|member|remove|cross|range|tocol|replace|divide|selected|message)\b</string>
			<key>name</key>
			<string>support.function.gro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>=|\:=|&lt;|&gt;|&amp;|\|</string>
			<key>name</key>
			<string>keyword.operator.logical.gro</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(program)\s+([^\s\(\\]+)(?:\s*(\([^\)]*\)))?\s+(:=)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.rgo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.gro</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.gro</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.control.gro</string>
				</dict>
			</dict>
			<key>end</key>
			<string>{</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.gro</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.gro</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?:if|then|else|end|let|needs|include|fun|sharing|program)\b</string>
			<key>name</key>
			<string>keyword.control.gro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\.</string>
			<key>name</key>
			<string>constant.character.escape.gro</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.gro</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.gro</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.gro</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\$?"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.gro</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.gro</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.gro</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\[\$`"\\\n]</string>
					<key>name</key>
					<string>constant.character.escape.gro</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolation</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f|ll|LL|ull|ULL)?\b</string>
			<key>name</key>
			<string>constant.numeric.gro</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.gro</string>
	<key>uuid</key>
	<string>938C0C95-AC20-4927-B73D-ABCA0D91FC99</string>
</dict>
</plist>
